import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { FileData, AnalysisResult, GeneratorType } from '../types';
import { generateContent } from '../services/geminiService';
import { Sparkles, Copy, Check, MessageSquare, FileText, Mail, Briefcase, FileDown, FileOutput, Printer, Settings, X, Download, AlertTriangle, Loader2, Share2, Link, ChevronDown } from 'lucide-react';

interface ContentGeneratorProps {
  resumeFile: FileData;
  jobDescription: string;
  analysis: AnalysisResult;
}

interface DocSettings {
  headerText: string;
  footerText: string;
  showDate: boolean;
}

const ContentGenerator: React.FC<ContentGeneratorProps> = ({ resumeFile, jobDescription, analysis }) => {
  const [activeTab, setActiveTab] = useState<GeneratorType>(GeneratorType.ATS_RESUME);
  const [generatedData, setGeneratedData] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  
  // Email Customization State
  const [emailRecipient, setEmailRecipient] = useState("Recruiter");
  
  // Specific loading states
  const [isDownloading, setIsDownloading] = useState<string | null>(null);

  // Settings State
  const [showSettings, setShowSettings] = useState(false);
  const [docSettings, setDocSettings] = useState<DocSettings>({
    headerText: 'MonuisHere | Career Architect Report',
    footerText: 'Generated by MonuisHere AI. Private & Confidential.',
    showDate: true
  });

  const handleGenerate = async (type: GeneratorType, forceRefresh = false) => {
    if (generatedData[type] && !forceRefresh) return; 

    setLoading(true);
    setError(null);
    setDownloadError(null);
    try {
      const content = await generateContent(
          type, 
          resumeFile, 
          jobDescription, 
          analysis,
          { emailRecipient: type === GeneratorType.EMAIL_TEMPLATE ? emailRecipient : undefined }
      );
      setGeneratedData(prev => ({ ...prev, [type]: content }));
    } catch (err: any) {
      setError(err.message || "Failed to generate content. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  React.useEffect(() => {
    if (!generatedData[activeTab] && !loading) {
      handleGenerate(activeTab);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeTab]);

  const copyToClipboard = () => {
    const text = generatedData[activeTab];
    if (text) {
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleShare = () => {
    const mockLink = `https://monuishere.ai/s/${Math.random().toString(36).substr(2, 8)}`;
    navigator.clipboard.writeText(mockLink);
    setShared(true);
    setTimeout(() => setShared(false), 3000);
  };

  const cleanFilename = (type: string, ext: string) => {
    return `MonuisHere_${type.replace(/[\s/]/g, '_')}_${new Date().toISOString().slice(0,10)}.${ext}`;
  };

  const handleDownloadPDF = async () => {
    setDownloadError(null);
    const content = generatedData[activeTab];
    if (!content) {
        setDownloadError("Content not ready for download.");
        return;
    }

    setIsDownloading('pdf');
    
    await new Promise(resolve => setTimeout(resolve, 500));

    try {
        const container = document.createElement('div');
        container.style.position = 'absolute';
        container.style.left = '-9999px';
        container.style.top = '0';
        container.style.width = '800px'; 
        container.style.padding = '40px';
        container.style.color = '#000';
        container.style.background = '#fff';
        container.style.fontFamily = 'Inter, sans-serif';
        
        // Header
        const header = document.createElement('div');
        header.style.borderBottom = '2px solid #F97316';
        header.style.paddingBottom = '10px';
        header.style.marginBottom = '20px';
        header.style.display = 'flex';
        header.style.justifyContent = 'space-between';
        header.style.alignItems = 'center';
        header.innerHTML = `
        <div>
            <h1 style="font-size: 16px; font-weight: bold; margin: 0; color: #18181B;">${docSettings.headerText}</h1>
            <p style="font-size: 10px; color: #71717A; margin: 0;">${activeTab}</p>
        </div>
        <div style="text-align: right;">
            ${docSettings.showDate ? `<p style="font-size: 10px; color: #71717A; margin: 0;">${new Date().toLocaleDateString()}</p>` : ''}
            <p style="font-size: 10px; color: #F97316; margin: 0; font-weight: bold;">Verified Output</p>
        </div>
        `;
        
        const body = document.createElement('div');
        body.className = 'markdown-body';
        
        const sourceElement = document.getElementById('generated-content');
        if (sourceElement) {
            body.innerHTML = sourceElement.innerHTML;
            const allElements = body.querySelectorAll('*');
            allElements.forEach(el => {
                if (el instanceof HTMLElement) {
                    el.style.color = '#18181b'; 
                    el.style.backgroundColor = 'transparent';
                    if (el.tagName === 'H1') {
                        el.style.fontSize = '24px';
                        el.style.borderBottom = '1px solid #e4e4e7';
                        el.style.marginBottom = '12px';
                    }
                    if (el.tagName === 'H2') {
                        el.style.color = '#ea580c';
                        el.style.fontSize = '18px';
                        el.style.marginTop = '20px';
                        el.style.marginBottom = '10px';
                    }
                    if (el.tagName === 'H3') {
                        el.style.fontSize = '14px';
                        el.style.fontWeight = 'bold';
                        el.style.marginTop = '16px';
                    }
                    if (el.tagName === 'P') {
                        el.style.fontSize = '11px';
                        el.style.lineHeight = '1.6';
                        el.style.marginBottom = '10px';
                    }
                    if (el.tagName === 'LI') {
                        el.style.fontSize = '11px';
                        el.style.marginBottom = '4px';
                    }
                    if (el.tagName === 'CODE') {
                        el.style.backgroundColor = '#f4f4f5';
                        el.style.border = '1px solid #e4e4e7';
                        el.style.padding = '2px 4px';
                        el.style.borderRadius = '4px';
                        el.style.fontFamily = 'monospace';
                        el.style.fontSize = '10px';
                    }
                    if (el.tagName === 'BLOCKQUOTE') {
                        el.style.borderLeft = '3px solid #ea580c';
                        el.style.paddingLeft = '10px';
                        el.style.color = '#52525b';
                        el.style.fontStyle = 'italic';
                    }
                }
            });
        } else {
            body.innerText = content;
        }

        const footer = document.createElement('div');
        footer.style.borderTop = '1px solid #E4E4E7';
        footer.style.marginTop = '30px';
        footer.style.paddingTop = '10px';
        footer.style.textAlign = 'center';
        footer.innerHTML = `
        <p style="font-size: 9px; color: #A1A1AA; margin: 0;">${docSettings.footerText}</p>
        `;

        container.appendChild(header);
        container.appendChild(body);
        container.appendChild(footer);
        document.body.appendChild(container);

        const opt = {
        margin: 0.5,
        filename: cleanFilename(activeTab, 'pdf'),
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
        };
        
        await (window as any).html2pdf().set(opt).from(container).save();
        document.body.removeChild(container);
    } catch (e) {
        console.error(e);
        setDownloadError("PDF Download Failed. Please check your browser permissions.");
    } finally {
        setIsDownloading(null);
    }
  };

  const handleDownloadODT = async () => {
    setDownloadError(null);
    const text = generatedData[activeTab];
    if (!text) {
         setDownloadError("Content not generated yet.");
         return;
    }
    
    setIsDownloading('odt');
    await new Promise(resolve => setTimeout(resolve, 300));

    try {
        const escapeXml = (unsafe: string) => unsafe.replace(/[<>&'"]/g, (c) => {
            switch (c) {
                case '<': return '&lt;';
                case '>': return '&gt;';
                case '&': return '&amp;';
                case '\'': return '&apos;';
                case '"': return '&quot;';
                default: return c;
            }
        });

        const lines = text.split('\n');
        let xmlBody = '';
        let listOpen = false;

        lines.forEach(line => {
            const trimmed = line.trim();
            if (trimmed === '') {
                if (listOpen) {
                    xmlBody += `</text:list>`;
                    listOpen = false;
                }
                return;
            }

            if (trimmed.startsWith('# ')) {
                xmlBody += `<text:h text:style-name="Heading_20_1" text:outline-level="1">${escapeXml(trimmed.substring(2))}</text:h>`;
            } else if (trimmed.startsWith('## ')) {
                xmlBody += `<text:h text:style-name="Heading_20_2" text:outline-level="2">${escapeXml(trimmed.substring(3))}</text:h>`;
            } else if (trimmed.startsWith('### ')) {
                xmlBody += `<text:h text:style-name="Heading_20_3" text:outline-level="3">${escapeXml(trimmed.substring(4))}</text:h>`;
            } 
            else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
                if (!listOpen) {
                    xmlBody += `<text:list text:style-name="List_20_1">`;
                    listOpen = true;
                }
                let content = trimmed.substring(2);
                content = content.replace(/\*\*(.*?)\*\*/g, '<text:span text:style-name="Bold">$1</text:span>');
                xmlBody += `<text:list-item><text:p>${content}</text:p></text:list-item>`;
            } 
            else {
                if (listOpen) {
                    xmlBody += `</text:list>`;
                    listOpen = false;
                }
                let content = escapeXml(trimmed);
                content = content.replace(/\*\*(.*?)\*\*/g, '<text:span text:style-name="Bold">$1</text:span>');
                content = content.replace(/\*(.*?)\*/g, '<text:span text:style-name="Italic">$1</text:span>');
                
                xmlBody += `<text:p text:style-name="Standard">${content}</text:p>`;
            }
        });

        if (listOpen) {
            xmlBody += `</text:list>`;
        }

        const fodtTemplate = `<?xml version="1.0" encoding="UTF-8"?>
    <office:document xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" 
    xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" 
    xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" 
    xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" 
    office:version="1.2" office:mimetype="application/vnd.oasis.opendocument.text">
    <office:automatic-styles>
    <style:style style:name="Bold" style:family="text"><style:text-properties fo:font-weight="bold"/></style:style>
    <style:style style:name="Italic" style:family="text"><style:text-properties fo:font-style="italic"/></style:style>
    <style:style style:name="Heading_20_1" style:display-name="Heading 1" style:family="paragraph" style:parent-style-name="Standard" style:next-style-name="Standard">
        <style:text-properties fo:font-size="18pt" fo:font-weight="bold" fo:color="#ea580c"/>
    </style:style>
    <style:style style:name="Heading_20_2" style:display-name="Heading 2" style:family="paragraph" style:parent-style-name="Standard" style:next-style-name="Standard">
        <style:text-properties fo:font-size="14pt" fo:font-weight="bold" fo:color="#18181b"/>
    </style:style>
    </office:automatic-styles>
    <office:body>
    <office:text>
    <text:p text:style-name="Standard" fo:font-weight="bold" fo:font-size="10pt" fo:color="#555555">${escapeXml(docSettings.headerText)}</text:p>
    <text:p text:style-name="Standard" fo:font-size="8pt" fo:color="#999999">${docSettings.showDate ? new Date().toLocaleDateString() : ''}</text:p>
    <text:p text:style-name="Standard"> </text:p>
    ${xmlBody}
    <text:p text:style-name="Standard"> </text:p>
    <text:p text:style-name="Standard" fo:font-size="8pt" fo:color="#999999" fo:text-align="center">${escapeXml(docSettings.footerText)}</text:p>
    </office:text>
    </office:body>
    </office:document>`;

        const element = document.createElement("a");
        const file = new Blob([fodtTemplate], {type: 'application/vnd.oasis.opendocument.text'});
        element.href = URL.createObjectURL(file);
        element.download = cleanFilename(activeTab, 'fodt'); 
        document.body.appendChild(element); 
        element.click();
        document.body.removeChild(element);
    } catch (e) {
        setDownloadError("ODT/Word Export Failed.");
    } finally {
        setIsDownloading(null);
    }
  };

  const handleDownloadCSV = async () => {
    setDownloadError(null);
    const text = generatedData[activeTab];
    if (!text) {
        setDownloadError("Content empty.");
        return;
    }

    setIsDownloading('csv');
    await new Promise(resolve => setTimeout(resolve, 300));

    try {
        const rows = [
            ["Document Type", activeTab],
            ["Generated Date", new Date().toISOString()],
            ["Application Name", "MonuisHere AI"],
            ["Content", text]
        ];

        const csvContent = rows.map(e => e.map(c => `"${c.replace(/"/g, '""')}"`).join(",")).join("\n");
        const element = document.createElement("a");
        const file = new Blob([csvContent], {type: 'text/csv'});
        element.href = URL.createObjectURL(file);
        element.download = cleanFilename(activeTab, 'csv');
        document.body.appendChild(element); 
        element.click();
        document.body.removeChild(element);
    } catch (e) {
        setDownloadError("CSV Export Failed. Try checking your browser's download settings.");
    } finally {
        setIsDownloading(null);
    }
  };

  const tabs = [
    { id: GeneratorType.ATS_RESUME, icon: FileOutput, label: 'Full ATS Resume' },
    { id: GeneratorType.RESUME_SUGGESTIONS, icon: Briefcase, label: 'Optimization' },
    { id: GeneratorType.COVER_LETTER, icon: FileText, label: 'Cover Letter' },
    { id: GeneratorType.INTERVIEW_PREP, icon: MessageSquare, label: 'Interview' },
    { id: GeneratorType.EMAIL_TEMPLATE, icon: Mail, label: 'Email' },
  ];

  return (
    <div className="flex flex-col h-full bg-zinc-950 relative">
      
      {/* Settings Modal */}
      <AnimatePresence>
        {showSettings && (
            <motion.div 
                initial={{ opacity: 0, y: -10, scale: 0.95 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: -10, scale: 0.95 }}
                className="absolute top-14 right-4 z-30 w-72 bg-zinc-900 border border-zinc-700 rounded-xl shadow-2xl p-4"
            >
                <div className="flex justify-between items-center mb-4 pb-2 border-b border-zinc-800">
                    <h3 className="text-sm font-bold text-white flex items-center gap-2">
                        <Settings className="w-3 h-3" />
                        Document Settings
                    </h3>
                    <button onClick={() => setShowSettings(false)} className="text-zinc-500 hover:text-white"><X className="w-4 h-4" /></button>
                </div>
                <div className="space-y-4">
                    <div>
                        <label className="text-[10px] uppercase text-zinc-500 font-mono block mb-1">Header Title</label>
                        <input 
                            type="text" 
                            value={docSettings.headerText}
                            onChange={(e) => setDocSettings(s => ({...s, headerText: e.target.value}))}
                            className="w-full bg-zinc-950 border border-zinc-800 rounded px-2 py-1.5 text-xs text-white focus:border-orange-500 outline-none transition-colors"
                        />
                    </div>
                    <div>
                        <label className="text-[10px] uppercase text-zinc-500 font-mono block mb-1">Footer Text</label>
                        <input 
                            type="text" 
                            value={docSettings.footerText}
                            onChange={(e) => setDocSettings(s => ({...s, footerText: e.target.value}))}
                            className="w-full bg-zinc-950 border border-zinc-800 rounded px-2 py-1.5 text-xs text-white focus:border-orange-500 outline-none transition-colors"
                        />
                    </div>
                    <div className="flex items-center gap-2 pt-2 border-t border-zinc-800/50">
                         <input 
                            type="checkbox"
                            checked={docSettings.showDate}
                            onChange={(e) => setDocSettings(s => ({...s, showDate: e.target.checked}))} 
                            id="showDate"
                            className="accent-orange-500 w-3 h-3"
                        />
                        <label htmlFor="showDate" className="text-xs text-zinc-400 cursor-pointer select-none">Include Date in Header</label>
                    </div>
                </div>
            </motion.div>
        )}
      </AnimatePresence>

      {/* 1. Header & Toolbar */}
      <div className="flex flex-col border-b border-zinc-800 bg-zinc-900/30 backdrop-blur-sm shrink-0">
        
        {/* Tab Navigation */}
        <div className="px-4 pt-4 overflow-x-auto scrollbar-hide">
          <div className="flex space-x-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`relative px-4 py-2 text-xs font-medium rounded-t-lg transition-all border-t border-x ${
                  activeTab === tab.id
                    ? 'text-white bg-zinc-950 border-zinc-800 border-b-zinc-950 translate-y-[1px] z-10'
                    : 'text-zinc-500 bg-zinc-900/50 border-transparent hover:text-zinc-300 hover:bg-zinc-800'
                }`}
              >
                <div className="flex items-center gap-2">
                  <tab.icon className={`w-3.5 h-3.5 ${activeTab === tab.id ? 'text-orange-500' : ''}`} />
                  {tab.label}
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Action Toolbar */}
        <div className="px-6 py-2 flex items-center justify-between border-t border-zinc-800 bg-zinc-900/50">
            <div className="flex items-center gap-4">
                <div className="flex items-center gap-2">
                  <div className={`w-2 h-2 rounded-full ${loading ? 'bg-orange-500 animate-pulse' : 'bg-green-500'}`}></div>
                  <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-wider hidden sm:inline">
                    {loading ? 'GENERATING_ASSETS...' : 'READY_TO_EXPORT'}
                  </span>
                </div>
                
                {/* Email Specific Toolbar */}
                {activeTab === GeneratorType.EMAIL_TEMPLATE && (
                   <div className="flex items-center gap-2 pl-4 border-l border-zinc-700/50">
                      <span className="text-[10px] text-zinc-500 font-mono">RECIPIENT:</span>
                      <div className="relative group">
                        <select 
                            value={emailRecipient}
                            onChange={(e) => {
                                setEmailRecipient(e.target.value);
                                // Trigger regeneration slightly after change or manual button
                            }}
                            className="bg-zinc-800 text-xs text-white border border-zinc-700 rounded pl-2 pr-6 py-1 appearance-none focus:border-orange-500 outline-none cursor-pointer"
                        >
                            <option value="Recruiter">Recruiter</option>
                            <option value="Hiring Manager">Hiring Manager</option>
                            <option value="LinkedIn Connection">LinkedIn Peer</option>
                        </select>
                        <ChevronDown className="w-3 h-3 text-zinc-400 absolute right-1.5 top-1.5 pointer-events-none" />
                      </div>
                      <button 
                        onClick={() => handleGenerate(activeTab, true)}
                        className="p-1 bg-zinc-800 hover:bg-orange-600 rounded text-zinc-400 hover:text-white transition-colors"
                        title="Regenerate for this recipient"
                      >
                         <Sparkles className="w-3 h-3" />
                      </button>
                   </div>
                )}
            </div>
            
            <div className="flex items-center gap-2">
                <button
                    onClick={() => setShowSettings(!showSettings)}
                    className={`p-1.5 rounded transition-colors ${showSettings ? 'bg-orange-500/20 text-orange-500' : 'text-zinc-400 hover:text-white hover:bg-zinc-800'}`}
                    title="Document Settings"
                >
                    <Settings className="w-3.5 h-3.5" />
                </button>
                
                <button
                    onClick={handleShare}
                    className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded transition-colors flex items-center gap-1 relative"
                    title="Create Share Link"
                >
                    {shared ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Share2 className="w-3.5 h-3.5" />}
                    <span className="text-[10px] font-bold font-mono hidden sm:inline">SHARE</span>
                </button>

                <div className="h-4 w-[1px] bg-zinc-800 mx-1"></div>
                
                <button
                    onClick={handleDownloadCSV}
                    disabled={!!isDownloading}
                    className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded transition-colors flex items-center gap-1"
                    title="Export CSV"
                >
                    {isDownloading === 'csv' ? <Loader2 className="w-3 h-3 animate-spin" /> : <span className="text-[10px] font-bold font-mono">CSV</span>}
                </button>
                <button
                    onClick={handleDownloadODT}
                    disabled={!!isDownloading}
                    className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded transition-colors flex items-center gap-1"
                    title="Export OSF/ODT (OpenDocument)"
                >
                    {isDownloading === 'odt' ? <Loader2 className="w-3 h-3 animate-spin" /> : <span className="text-[10px] font-bold font-mono">ODT</span>}
                </button>
                <button
                    onClick={handleDownloadPDF}
                    disabled={!!isDownloading}
                    className="flex items-center gap-1.5 px-3 py-1 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-[10px] font-bold rounded border border-zinc-700 transition-colors ml-1 disabled:opacity-50"
                >
                    {isDownloading === 'pdf' ? <Loader2 className="w-3 h-3 animate-spin" /> : <FileDown className="w-3 h-3" />}
                    PDF
                </button>
                <button
                    onClick={copyToClipboard}
                    className="flex items-center gap-1.5 px-3 py-1 bg-orange-600 hover:bg-orange-500 text-white text-[10px] font-bold rounded shadow-lg shadow-orange-900/20 transition-colors ml-1"
                >
                    {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                    {copied ? 'COPIED' : 'COPY'}
                </button>
            </div>
        </div>
      </div>

      {/* 2. Editor / Content Area */}
      <div className="flex-1 overflow-y-auto custom-scrollbar relative p-8 md:px-12 max-w-5xl mx-auto w-full">
         
         {/* Download Error Toast */}
         <AnimatePresence>
            {downloadError && (
                 <motion.div 
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    className="absolute top-4 left-1/2 -translate-x-1/2 z-50 bg-red-950/80 border border-red-900 text-red-200 px-4 py-2 rounded-lg text-xs flex items-center gap-2 backdrop-blur-md shadow-xl"
                 >
                    <AlertTriangle className="w-4 h-4" />
                    {downloadError}
                    <button onClick={() => setDownloadError(null)} className="ml-2 hover:text-white"><X className="w-3 h-3" /></button>
                 </motion.div>
            )}
             {shared && (
                 <motion.div 
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    className="absolute top-4 left-1/2 -translate-x-1/2 z-50 bg-green-950/80 border border-green-900 text-green-200 px-4 py-2 rounded-lg text-xs flex items-center gap-2 backdrop-blur-md shadow-xl"
                 >
                    <Link className="w-4 h-4" />
                    Secure Link Copied to Clipboard
                 </motion.div>
            )}
         </AnimatePresence>

         {loading ? (
            <div className="absolute inset-0 flex flex-col items-center justify-center bg-zinc-950/80 backdrop-blur-[1px] z-10">
              <div className="relative mb-4">
                 <div className="w-12 h-12 border-2 border-zinc-800 rounded-full"></div>
                 <div className="absolute inset-0 w-12 h-12 border-2 border-orange-500 border-t-transparent rounded-full animate-spin"></div>
              </div>
              <p className="text-zinc-500 font-mono text-xs animate-pulse">Processing natural language...</p>
            </div>
         ) : null}

         {error && (
            <div className="absolute inset-0 flex flex-col items-center justify-center bg-zinc-950 z-20">
                <div className="p-6 bg-red-950/20 border border-red-900/30 rounded-xl text-center max-w-md">
                    <div className="w-12 h-12 rounded-full bg-red-900/20 flex items-center justify-center mx-auto mb-4">
                        <X className="w-6 h-6 text-red-500" />
                    </div>
                    <h3 className="text-red-400 font-bold mb-2">Generation Failed</h3>
                    <p className="text-zinc-400 text-sm mb-6 leading-relaxed">{error}</p>
                    <button 
                    onClick={() => handleGenerate(activeTab, true)}
                    className="px-6 py-2 bg-red-900/30 hover:bg-red-900/50 text-red-200 rounded-lg text-xs font-mono border border-red-800/50 transition-colors"
                    >
                    RETRY OPERATION
                    </button>
                </div>
            </div>
         )}

         <AnimatePresence mode="wait">
             <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
              id="generated-content"
              className="prose prose-invert prose-zinc max-w-none prose-headings:font-sans prose-headings:tracking-tight prose-p:leading-relaxed prose-li:text-zinc-300 prose-strong:text-white pb-20"
             >
                {generatedData[activeTab] ? (
                    <ReactMarkdown
                        components={{
                            h1: ({node, ...props}) => <h1 className="text-3xl font-bold text-white mb-6 pb-4 border-b border-zinc-800" {...props} />,
                            h2: ({node, ...props}) => <h2 className="text-xl font-semibold text-orange-500 mt-8 mb-4 flex items-center gap-2" {...props} />,
                            h3: ({node, ...props}) => <h3 className="text-lg font-medium text-white mt-6 mb-3" {...props} />,
                            ul: ({node, ...props}) => <ul className="space-y-2 my-4 pl-4" {...props} />,
                            li: ({node, ...props}) => (
                                <li className="flex items-start gap-2 text-zinc-300">
                                <span className="mt-2.5 w-1 h-1 bg-zinc-500 rounded-full shrink-0" />
                                <span className="flex-1">{props.children}</span>
                                </li>
                            ),
                            p: ({node, ...props}) => <p className="mb-4 text-zinc-300 whitespace-pre-wrap break-words" {...props} />,
                            code: ({node, ...props}) => <code className="bg-zinc-900 text-orange-400 px-1.5 py-0.5 rounded border border-zinc-800 text-xs font-mono" {...props} />,
                            blockquote: ({node, ...props}) => <blockquote className="border-l-2 border-orange-500 pl-4 py-1 my-4 bg-zinc-900/30 italic text-zinc-400 rounded-r-lg" {...props} />,
                        }}
                    >
                        {generatedData[activeTab]}
                    </ReactMarkdown>
                ) : !loading && (
                    <div className="flex flex-col items-center justify-center py-20 opacity-50">
                        <Printer className="w-12 h-12 text-zinc-700 mb-4" />
                        <p className="text-zinc-600 font-mono text-sm">Waiting for content...</p>
                    </div>
                )}
             </motion.div>
         </AnimatePresence>
      </div>
    </div>
  );
};

export default ContentGenerator;